ecomm/ecomm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', include('toko.urls', namespace='toko')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomm/toko/urls.py
from django.urls import path
from . import views

app_name = 'toko'

urlpatterns = [
     path('', views.HomeListView.as_view(), name='home-produk-list'),
     path('search/', views.search_view, name='search'),
     path('product/<slug>/', views.ProductDetailView.as_view(), name='produk-detail'),
     path('checkout/', views.CheckoutView.as_view(), name='checkout'),
     path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
     path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
     path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
     path('payment/<payment_method>', views.PaymentView.as_view(), name='payment'),
     path('paypal-return/', views.paypal_return, name='paypal-return'),
     path('paypal-cancel/', views.paypal_cancel, name='paypal-cancel'),
     path('contact/', views.ContactView.as_view(), name='contact'),
     path('kontak-success/', views.ContactSuccessView.as_view(), name='kontak-success'),
]

ecomm/toko/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

PILIHAN_KATEGORI = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

PILIHAN_LABEL = (
    ('NEW', 'primary'),
    ('SALE', 'info'),
    ('BEST', 'danger'),
)

PILIHAN_PEMBAYARAN = (
    ('P', 'Paypal'),
    ('S', 'Stripe'),
)

User = get_user_model()

class ProdukItem(models.Model):
    nama_produk = models.CharField(max_length=100)
    harga = models.FloatField()
    harga_diskon = models.FloatField(blank=True, null=True)
    slug = models.SlugField(unique=True)
    deskripsi = models.TextField()
    gambar = models.ImageField(upload_to='product_pics')
    label = models.CharField(choices=PILIHAN_LABEL, max_length=4)
    kategori = models.CharField(choices=PILIHAN_KATEGORI, max_length=2)

    def __str__(self):
        return f"{self.nama_produk} - ${self.harga}"

    def get_absolute_url(self):
        return reverse("toko:produk-detail", kwargs={
            "slug": self.slug
            })

    def get_add_to_cart_url(self):
        return reverse("toko:add-to-cart", kwargs={
            "slug": self.slug
            })
    
    def get_remove_from_cart_url(self):
        return reverse("toko:remove-from-cart", kwargs={
            "slug": self.slug
            })
            
    def get_related_products(self):
        return ProdukItem.objects.exclude(id=self.id)[:4]

    
class OrderProdukItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    produk_item = models.ForeignKey(ProdukItem, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.produk_item.nama_produk}"

    def get_total_harga_item(self):
        return self.quantity * self.produk_item.harga
    
    def get_total_harga_diskon_item(self):
        return self.quantity * self.produk_item.harga_diskon

    def get_total_hemat_item(self):
        return self.get_total_harga_item() - self.get_total_harga_diskon_item()
    
    def get_total_item_keseluruan(self):
        if self.produk_item.harga_diskon:
            return self.get_total_harga_diskon_item()
        return self.get_total_harga_item()
    
    def get_total_hemat_keseluruhan(self):
        if self.produk_item.harga_diskon:
            return self.get_total_hemat_item()
        return 0


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    produk_items = models.ManyToManyField(OrderProdukItem)
    tanggal_mulai = models.DateTimeField(auto_now_add=True)
    tanggal_order = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    alamat_pengiriman = models.ForeignKey('AlamatPengiriman', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

     
    def get_total_harga_order(self):
        total = 0
        for order_produk_item in self.produk_items.all():
            total += order_produk_item.get_total_item_keseluruan()
        return total
    
    def get_total_hemat_order(self):
        total = 0
        for order_produk_item in self.produk_items.all():
            total += order_produk_item.get_total_hemat_keseluruhan()
        return total

class AlamatPengiriman(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    alamat_1 = models.CharField(max_length=100)
    alamat_2 = models.CharField(max_length=100)
    negara = models.CharField(max_length=100)
    kode_pos = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.user.username} - {self.alamat_1}"

    class Meta:
        verbose_name_plural = 'AlamatPengiriman'

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
    payment_option = models.CharField(choices=PILIHAN_PEMBAYARAN, max_length=1)
    charge_id = models.CharField(max_length=50)

    def __self__(self):
        return self.user.username
    
    def __str__(self):
        return f"{self.user.username} - {self.payment_option} - {self.amount}"
    
    class Meta:
        verbose_name_plural = 'Payment'

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    message = models.TextField()

    def __str__(self):
        return self.name

ecomm/ecomm/templates/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.utils import timezone
from django.views import generic
from paypal.standard.forms import PayPalPaymentsForm
from django.db.models import Q
from django.views.generic import TemplateView
from .forms import CheckoutForm, ContactForm
from .models import ProdukItem, OrderProdukItem, Order, AlamatPengiriman, Payment, Contact
from django.core.mail import send_mail
from django.views.decorators.csrf import ensure_csrf_cookie
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator



class HomeListView(generic.ListView):
    template_name = 'home.html'
    queryset = ProdukItem.objects.all()
    paginate_by = 8

    def get_queryset(self):
        kategori = self.request.GET.get('kategori')
        if kategori:
            queryset = ProdukItem.objects.filter(kategori=kategori).order_by('kategori')
        else:
            queryset = ProdukItem.objects.all().order_by('kategori')
        return queryset
  
@method_decorator(ensure_csrf_cookie, name='dispatch')
class ProductDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'product_detail.html'
    model = ProdukItem

    def get_object(self, queryset=None):
        obj = get_object_or_404(self.model, slug=self.kwargs['slug'])
        return obj

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.object.is_accessible_by_user(request.user):
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

class CheckoutView(LoginRequiredMixin, generic.FormView):
    def get(self, *args, **kwargs):
        form = CheckoutForm()
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if order.produk_items.count() == 0:
                messages.warning(self.request, 'Belum ada belajaan yang Anda pesan, lanjutkan belanja')
                return redirect('toko:home-produk-list')
        except ObjectDoesNotExist:
            order = {}
            messages.warning(self.request, 'Belum ada belajaan yang Anda pesan, lanjutkan belanja')
            return redirect('toko:home-produk-list')

        context = {
            'form': form,
            'keranjang': order,
        }
        template_name = 'checkout.html'
        return render(self.request, template_name, context)

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                alamat_1 = form.cleaned_data.get('alamat_1')
                alamat_2 = form.cleaned_data.get('alamat_2')
                negara = form.cleaned_data.get('negara')
                kode_pos = form.cleaned_data.get('kode_pos')
                opsi_pembayaran = form.cleaned_data.get('opsi_pembayaran')
                alamat_pengiriman = AlamatPengiriman(
                    user=self.request.user,
                    alamat_1=alamat_1,
                    alamat_2=alamat_2,
                    negara=negara,
                    kode_pos=kode_pos,
                )

                alamat_pengiriman.save()
                order.alamat_pengiriman = alamat_pengiriman
                order.save()
                if opsi_pembayaran == 'P':
                    return redirect('toko:payment', payment_method='paypal')
                else:
                    return redirect('toko:payment', payment_method='stripe')

            messages.warning(self.request, 'Gagal checkout')
            return redirect('toko:checkout')
        except ObjectDoesNotExist:
            messages.error(self.request, 'Tidak ada pesanan yang aktif')
            return redirect('toko:order-summary')

class PaymentView(LoginRequiredMixin, generic.FormView):
    def get(self, *args, **kwargs):
        template_name = 'payment.html'
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            
            paypal_data = {
                'business': settings.PAYPAL_RECEIVER_EMAIL,
                'amount': order.get_total_harga_order,
                'item_name': f'Pembayaran belajanan order: {order.id}',
                'invoice': f'{order.id}-{timezone.now().timestamp()}' ,
                'currency_code': 'USD',
                'notify_url': self.request.build_absolute_uri(reverse('paypal-ipn')),
                'return_url': self.request.build_absolute_uri(reverse('toko:paypal-return')),
                'cancel_return': self.request.build_absolute_uri(reverse('toko:paypal-cancel')),
            }
        
            qPath = self.request.get_full_path()
            isPaypal = 'paypal' in qPath
        
            form = PayPalPaymentsForm(initial=paypal_data)
            context = {
                'paypalform': form,
                'order': order,
                'is_paypal': isPaypal,
            }
            return render(self.request, template_name, context)

        except ObjectDoesNotExist:
            return redirect('toko:checkout')


class OrderSummaryView(LoginRequiredMixin, generic.TemplateView):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'keranjang': order
            }
            template_name = 'order_summary.html'
            return render(self.request, template_name, context)
        except ObjectDoesNotExist:
            messages.error(self.request, 'Tidak ada pesanan yang aktif')
            return redirect('/')

def add_to_cart(request, slug):
    if request.user.is_authenticated:
        produk_item = get_object_or_404(ProdukItem, slug=slug)
        order_produk_item, _ = OrderProdukItem.objects.get_or_create(
            produk_item=produk_item,
            user=request.user,
            ordered=False
        )
        order_query = Order.objects.filter(user=request.user, ordered=False)
        if order_query.exists():
            order = order_query[0]
            if order.produk_items.filter(produk_item__slug=produk_item.slug).exists():
                order_produk_item.quantity += 1
                order_produk_item.save()
                pesan = f"ProdukItem sudah diupdate menjadi: { order_produk_item.quantity }"
                messages.info(request, pesan)
                return redirect('toko:produk-detail', slug = slug)
            else:
                order.produk_items.add(order_produk_item)
                messages.info(request, 'ProdukItem pilihanmu sudah ditambahkan')
                return redirect('toko:produk-detail', slug = slug)
        else:
            tanggal_order = timezone.now()
            order = Order.objects.create(user=request.user, tanggal_order=tanggal_order)
            order.produk_items.add(order_produk_item)
            messages.info(request, 'ProdukItem pilihanmu sudah ditambahkan')
            return redirect('toko:produk-detail', slug = slug)
    else:
        return redirect('/accounts/login')

def remove_from_cart(request, slug):
    if request.user.is_authenticated:
        produk_item = get_object_or_404(ProdukItem, slug=slug)
        order_query = Order.objects.filter(
            user=request.user, ordered=False
        )
        if order_query.exists():
            order = order_query[0]
            if order.produk_items.filter(produk_item__slug=produk_item.slug).exists():
                try: 
                    order_produk_item = OrderProdukItem.objects.filter(
                        produk_item=produk_item,
                        user=request.user,
                        ordered=False
                    )[0]
                    
                    order.produk_items.remove(order_produk_item)
                    order_produk_item.delete()

                    pesan = f"ProdukItem sudah dihapus"
                    messages.info(request, pesan)
                    return redirect('toko:produk-detail',slug = slug)
                except ObjectDoesNotExist:
                    print('Error: order ProdukItem sudah tidak ada')
            else:
                messages.info(request, 'ProdukItem tidak ada')
                return redirect('toko:produk-detail',slug = slug)
        else:
            messages.info(request, 'ProdukItem tidak ada order yang aktif')
            return redirect('toko:produk-detail',slug = slug)
    else:
        return redirect('/accounts/login')

# @csrf_exempt
def paypal_return(request):
    if request.user.is_authenticated:
        try:
            print('paypal return', request)
            order = Order.objects.get(user=request.user, ordered=False)
            payment = Payment()
            payment.user=request.user
            payment.amount = order.get_total_harga_order()
            payment.payment_option = 'P' # paypal kalai 'S' stripe
            payment.charge_id = f'{order.id}-{timezone.now()}'
            payment.timestamp = timezone.now()
            payment.save()
            
            order_produk_item = OrderProdukItem.objects.filter(user=request.user,ordered=False)
            order_produk_item.update(ordered=True)
            
            order.payment = payment
            order.ordered = True
            order.save()

            messages.info(request, 'Pembayaran sudah diterima, terima kasih')
            return redirect('toko:home-produk-list')
        except ObjectDoesNotExist:
            messages.error(request, 'Periksa kembali pesananmu')
            return redirect('toko:order-summary')
    else:
        return redirect('/accounts/login')

# @csrf_exempt
def paypal_cancel(request):
    messages.error(request, 'Pembayaran dibatalkan')

ecomm/ecomm/templates/home.html
{% extends 'base.html' %}

{% block content %}

{% include 'carousel.html' %}

<!--Main layout-->
<main>
    <div class="container">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: #607D8B">
            <!-- Container wrapper -->
            <div class="container-fluid">

                <!-- Navbar brand -->
                <a class="navbar-brand" href="#">Categories:</a>

                <!-- Toggle button -->
                <button
                        class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent2"
                        aria-controls="navbarSupportedContent2"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent2">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                        <!-- Link -->
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'toko:home-produk-list' %}?kategori=">All
                            <span class="sr-only">(current)</span>
                          </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'toko:home-produk-list' %}?kategori=S">Shirts</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'toko:home-produk-list' %}?kategori=SW">Sport wears</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'toko:home-produk-list' %}?kategori=OW">Outwears</a>
                        </li>
                      </ul> 
            
                      {% regroup produk_list by kategori as kategori_list %}
      
                      {% for kategori in kategori_list %}
                        <h2>{{ kategori.grouper }}</h2>
                        {% for produk in kategori.list %}
                        <div>
                           <!-- Tampilkan informasi produk -->
                          <p>{{ produk.nama_produk }}</p>
                          <p>{{ produk.harga }}</p>
                          <!-- ... -->
                        </div>
                        {% endfor %}
                      {% endfor %}
      
                      </ul>
      
                    </ul>

                    <!-- Search -->
                    <form action="{% url 'toko:search' %}" method="GET">
                      <input type="text" name="query" placeholder="Cari produk...">
                      <button type="submit">Cari</button>
                    </form>

                </div>
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->

        <!-- Products -->
        <section>
            <div class="text-center">
              <div class="row">
                
                {% for pItem in object_list %}
                <div class="col-lg-3 col-md-6 mb-4">
                  <div class="card">
                    <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                      data-mdb-ripple-color="light">
                      <img src="{{ pItem.gambar.url }}"
                        class="w-100" />
                      <a href="{{ pItem.get_absolute_url }}"> 
                        <div class="mask">
                          <div class="d-flex justify-content-start align-items-end h-100">
                            <h5><span class="badge bg-{{ pItem.get_label_display }} ms-2">{{ pItem.label }}</span></h5>
                          </div>
                        </div>
                        <div class="hover-overlay">
                          <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                        </div>
                      </a>
                    </div>
                    <div class="card-body">
                      <a href="{{ pItem.get_absolute_url }}" class="text-reset">
                        <h5 class="card-title mb-2">{{ pItem.nama_produk }}</h5>
                      </a>
                      <a href="" class="text-reset ">
                        <p>{{ pItem.get_kategori_display }}</p>
                      </a>
                      <h6 class="mb-3 price">${% if pItem.harga_diskon %}{{ pItem.harga_diskon }}{% else %}{{ pItem.harga }}{% endif %}</h6>
                    </div>
                  </div>
                </div>
                {% empty %}
                  <p>Data Produk belum tersedia</p>
                {% endfor %}

              </div>
            </div>
          </section>
        <!-- End Products -->

        <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-3">
            <ul class="pagination">
                <li class="page-item">
                  {% if page_obj.has_previous %}
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                  {% endif %}
                </li>
                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                <li class="page-item">
                  {% if page_obj.has_next %}
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                  {% endif %}
                </li>
            </ul>
        </nav>
        {% endif %}
        <!-- Pagination -->
    </div>
</main>
<!--Main layout-->
{% endblock content %}

ecomm/ecomm/templates/product_detail.html
{% extends 'base.html' %}

{% block content%}

<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container mt-5">
        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <img src="{{ object.gambar.url }}" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <!--Content-->
                <div class="p-4">
                    <div class="mb-3">
                        <a href="">
                            <span class="badge bg-dark me-1">{{ object.get_kategori_display }}</span>
                        </a>
                        {% if object.label == 'NEW' %}
                        <a href="">
                            <span class="badge bg-{{ object.get_label_display }} me-1">New</span>
                        </a>
                        {% elif object.label == 'SALE' %}
                        <a href="">
                            <span class="badge bg-{{ object.get_label_display }} me-1">Sale</span>
                        </a>
                        {% else %}
                        <a href="">
                            <span class="badge bg-{{ object.get_label_display }} me-1">Bestseller</span>
                        </a>
                        {% endif %}
                    </div>

                    <p class="lead">
                        {% if object.harga_diskon %}
                        <span class="me-1">
                            <del>${{ object.harga }}</del>
                        </span>
                        <span>${{ object.harga_diskon }}</span>
                        {% else %}
                        <span>${{ object.harga }}</span>
                        {% endif %}
                    </p>

                    <strong><p style="font-size: 20px;">Deskripsi</p></strong>

                    <p>{{ object.deskripsi }}</p>
                    <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary ms-1">
                        Tambah ke keranjang
                        <i class="fas fa-shopping-cart ms-1"></i>
                    </a>
                    <form action="{{ object.get_remove_from_cart_url }}" method="POST" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger ms-1">
                            Kurangi keranjang
                            <i class="fas fa-shopping-cart ms-1"></i>
                        </button>
                    </form>
                    
                </div>
                <!--Content-->
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->

        <hr />

        <!--Grid row-->
        <div class="row d-flex justify-content-center">
           <!--Additional information-->
           <!--Grid row-->
<div class="row d-flex justify-content-center">
    <!--Additional information-->
    <div class="row d-flex justify-content-center">
       
</div>
<!--Grid row-->

        <div class="mt-4">
            <h5>Produk Lainnya:</h5>
            <li class="list-group-item">
                <div class="row related-products">
                    {% for product in object.get_related_products %}
                    <div class="col-md-3">
                        <div class="card">
                            <img src="{{ product.gambar.url }}" alt="{{ product.nama_produk }}" class="card-img-top">
                            <div class="card-body">
                                <h5 class="card-title">{{ product.nama_produk }}</h5>
                                <p class="card-text">${{ product.harga }}</p>
                                <a href="{{ product.get_absolute_url }}" class="btn btn-primary">View Details</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </li>
        </div>

<!--Additional information-->


        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->
{% endblock content%}

ecomm/ecomm/templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

ecomm/ecomm/templates/search.html
{% extends 'base.html' %}

{% block content %}
    <!-- Products -->
    <div class="container">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-dark mt-1 mb-4 shadow p-2" style="background-color: #d12b0ed2">
        <!-- Container wrapper -->
          <div class="container-fluid">

              <!-- Navbar brand -->
              <a class="navbar-brand" href="#">Categories:</a>

              <!-- Toggle button -->
              <button
                      class="navbar-toggler"
                      type="button"
                      data-mdb-toggle="collapse"
                      data-mdb-target="#navbarSupportedContent2"
                      aria-controls="navbarSupportedContent2"
                      aria-expanded="false"
                      aria-label="Toggle navigation">
                  <i class="fas fa-bars"></i>
              </button>

              <!-- Collapsible wrapper -->
              <div class="collapse navbar-collapse" id="navbarSupportedContent2">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <!-- Link -->
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'toko:home-produk-list' %}?kategori=">All
                        <span class="sr-only">(current)</span>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'toko:home-produk-list' %}?kategori=S">Shirts</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'toko:home-produk-list' %}?kategori=SW">Sport wears</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'toko:home-produk-list' %}?kategori=OW">Outwears</a>
                    </li>
                  </ul> 
        
                  {% regroup produk_list by kategori as kategori_list %}
  
                  {% for kategori in kategori_list %}
                    <h2>{{ kategori.grouper }}</h2>
                    {% for produk in kategori.list %}
                    <div>
                       <!-- Tampilkan informasi produk -->
                      <p>{{ produk.nama_produk }}</p>
                      <p>{{ produk.harga }}</p>
                      <!-- ... -->
                    </div>
                    {% endfor %}
                  {% endfor %}
  
                  </ul>
  
                </ul>

                <!-- Search -->
                <form action="{% url 'toko:search' %}" method="GET">
                  <input type="text" name="query" placeholder="Cari produk...">
                  <button type="submit">Cari</button>
                </form>

            </div>
        </div>
        <!-- Container wrapper -->

    </nav>

    <section>
        <div class="text-center">
            <div class="row">
                {% for pItem in results %}
                <div class="col-lg-3 col-md-6 mb-4">
                    <div class="card">
                        <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                            data-mdb-ripple-color="light">
                            <img src="{{ pItem.gambar.url }}" class="w-100" />
                            <a href="{{ pItem.get_absolute_url }}">
                                <div class="mask">
                                    <div class="d-flex justify-content-start align-items-end h-100">
                                        <h5><span class="badge bg-{{ pItem.get_label_display }} ms-2">{{ pItem.label }}</span></h5>
                                    </div>
                                </div>
                                <div class="hover-overlay">
                                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                </div>
                            </a>
                        </div>
                        <div class="card-body">
                            <a href="{{ pItem.get_absolute_url }}" class="text-reset">
                                <h5 class="card-title mb-2">{{ pItem.nama_produk }}</h5>
                            </a>
                            <a href="" class="text-reset ">
                                <p>{{ pItem.get_kategori_display }}</p>
                            </a>
                            <h6 class="mb-3 price">${% if pItem.harga_diskon %}{{ pItem.harga_diskon }}{% else %}{{ pItem.harga }}{% endif %}</h6>
                        </div>
                    </div>
                </div>
                {% empty %}
                <p>Data Produk belum tersedia</p>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- End Products -->
{% endblock %}